const KEY_LEFT = 37;
const KEY_UP = 38;
const KEY_RIGHT = 39;
const KEY_DOWN = 40;
const LOCAL_STORAGE_TOP_RESULTS_NAME = 'topResults';
const LOCAL_STORAGE_TOP_RESULTS_COUNT = 10;
const LOCAL_STORAGE_GAME_STATE = 'gameState';

export {
  KEY_LEFT,
  KEY_UP,
  KEY_RIGHT,
  KEY_DOWN,
  LOCAL_STORAGE_TOP_RESULTS_NAME,
  LOCAL_STORAGE_TOP_RESULTS_COUNT,
  LOCAL_STORAGE_GAME_STATE,
}